services:
  db:
    image: postgres:latest
    container_name: roadmapOs-db
    restart: always
    environment:
      POSTGRES_USER: midzuhara
      POSTGRES_PASSWORD: 6666
      POSTGRES_DB: roadmapOs-db
    ports:
      - "5434:5432"
    volumes:
      - data:/var/lib/postgresql

volumes:
  data: