spring:

  application:
    name: RoadmapOS

  datasource:
    password: 6666
    username: midzuhara
    url: jdbc:postgresql://localhost:5434/roadmapOs-db
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 10 # Группировать по 10 запросов
          order_inserts: true
          order_updates: true


  flyway:
    enabled: true
    locations: classpath:db/migration


grpc:
  client:
    validator-client:
      address: static://localhost:50051
      negotiation-type: plaintext